apiVersion: v1
kind: Pod
metadata:
  name: multiple-mount
spec:
  containers:
  - name: secret
    image: nginx
    ports:
      - containerPort: 80
    env:
      - name: secret-name-1
        valueFrom:
          secretKeyRef:
            name: secret1
            key: Name
      - name: secret-name-2
        valueFrom:
          secretKeyRef:
            name: secret2
            key: client
      - name: secret-name-3
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: Cloud
    

