apiVersion: v1
kind: Pod
metadata:
  name: secret-example
spec:
  containers:
  - name: secret
    image: nginx
    ports:
      - containerPort: 80
    envFrom:
      - secretRef:
          name: secret1
      - secretRef:
          name: secret2
      - secretRef:
          name: mysecret

