apiVersion: v1
kind: Pod
metadata:
  name: config-map
spec:
  containers:
  - name: config-map
    image: nginx
    env:
      - name: Configmap-pod-1
        volumeFrom:
          configMapKeyRef:
            name: cm
            key: APP_ENV
      - name: Configmap-pod-2
        volumeFrom:
          configMapKeyRef:
            name: config-map
            key: Cicd 
      - name: Configmap-pod-3
        volumeFrom:
          configMapKeyRef:
            name: cm3
            key: env